#pragma once

enum MenuOptionsCode{
    NO_CHANGES,
    START_GAME,
    OPEN_OPTIONS,
    OPEN_CHOOSE_LEVEL_MENU,
    QUIT_TO_DESKTOP,
    QUIT_TO_MAIN_MENU,
    CHOOSE_LVL1,
    CHOOSE_LVL2,
    CHOOSE_LVL3,
    CHOOSE_LVL4
};
